#### Course ML Zoomcamp Homework 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [3]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

<b>1. What's the version of NumPy that you installed?</b>

In [4]:
np.__version__

'1.21.5'

<b>2. How many records are in the dataset?</b>

In [5]:
data.shape

(11914, 16)

In [8]:
data.shape[0]    # Returns number of rows

11914

In [11]:
len(data)    # Returns number of rows

11914

In [9]:
data.shape[1]    # Returns number of columns

16

<b>3. Who are the most frequent car manufacturers (top-3) according to the dataset?</b>

In [12]:
data['Make'].value_counts().nlargest(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [13]:
data['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

<b>4. What's the number of unique Audi car models in the dataset?</b>

In [32]:
unique_audi_car_models_number = data[(data['Make']=='Audi')]['Model'].nunique()
print(unique_audi_car_models_number)

34


<b>5. How many columns in the dataset have missing values?</b>

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

    5 columns

<b>6.</b>
- Find the median value of "Engine Cylinders" column in the dataset.
- Next, calculate the most frequent value of the same "Engine Cylinders".
- Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
- Now, calculate the median value of "Engine Cylinders" once again.
- Has it changed?

In [24]:
engine_cylinder_median = data['Engine Cylinders'].median()
print(engine_cylinder_median)

6.0


In [21]:
engine_cylinder_mode = data['Engine Cylinders'].mode()
print(engine_cylinder_mode)

0    4.0
Name: Engine Cylinders, dtype: float64


In [25]:
engine_cylinder_missing_value_mode = data['Engine Cylinders'].fillna(value=engine_cylinder_mode)
print(engine_cylinder_missing_value_mode)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64


In [28]:
new_median_engine_cylinder = engine_cylinder_missing_value_mode.median()
print(new_median_engine_cylinder)

6.0


In [30]:
engine_cylinder_missing_value_mode.isnull().sum()

30

<b>7.</b>
- Select all the "Lotus" cars from the dataset.
- Select only columns "Engine HP", "Engine Cylinders".
- Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the value of the first element of w?

In [34]:
lotus_cars = data_new=data[data["Make"]=="Lotus"]
# print(lotus_cars)

In [36]:
lotus_cars_selected_cols = lotus_cars[["Engine HP", "Engine Cylinders"]]
lotus_cars_selected_cols

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [37]:
lotus_cars_selected_cols.duplicated().any()

True

In [38]:
len(lotus_cars_selected_cols.duplicated())

29

In [39]:
data_drop_duplicates = lotus_cars_selected_cols.drop_duplicates()
data_drop_duplicates

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [41]:
X = data_drop_duplicates.iloc[:,:].values

In [42]:
X[:,:]

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [46]:
XTX = np.dot(X.T,X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [47]:
XTX.shape

(2, 2)

In [48]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [49]:
X_inv = np.linalg.inv(XTX)

In [51]:
Y = np.dot(X_inv, X.T)

In [54]:
w = np.dot(Y, y)
w

array([  4.59494481, -63.56432501])